### ISSUE TITLE
Implement as a babel plugin?

### ISSUE THREAD

**Issue by bebraw** [zackify/react-easy-test#1]
Would it make sense to push the idea to Babel level?

**Comment by zackify** [comment]
How would that look? I don't see how it could help.

**Comment by bebraw** [comment]
It would allow you to solve `Decorator needs to be removed unless testing.` easily.

The concept sort of reminds me of Python's doctests in a good way. That actually would be another approach. I don't think there's doctest for React yet.

**Comment by zackify** [comment]
Why that over a webpack loader? I guess it doesn't matter

**Comment by bebraw** [comment]
@zackify Well, there are guys using browserify etc. still. :)

**Comment by zackify** [comment]
move discussion here https://github.com/Legitcode/inline-tests want to help work on it?

**Comment by bebraw** [comment]
@zackify I'm a little swamped with work atm. I subscribed to the repo, though. Btw, please see https://github.com/thejameskyle/babel-plugin-handbook and http://phabricator.babeljs.io/T2645 . Apparently decorators are broken in Babel 6 and the decorator proposal has changed...

**Comment by zackify** [comment]
Thanks. And I know that they are broke which is why I'm using Babel 5 for
now :/ pretty annoying.
